
jwt:
  secret-key: ad861fbe42d6d4517997caaac85748c7b33ac43b0eb3d6fe19126eba998c1bb5c29f6110dd5e5d45c287462bc2cbd90865485e93e313717260b3a054c9d355a7
  token:
#    expiration-time: 3600 #1시간
    expiration-time: 604800
    refresh-expiration-time: 2592000

oauth:
  kakao:
    client-id: f3474b073f9c02883e0b9ac53d7cbead
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-url: http://localhost:3000/login #프론트
#      redirect-url: http://songssam.site:3000/login #서버
#      redirect-url: http://localhost:8080 #로컬
cloud:
  aws:
    s3:
      bucket: songssam.site
    credentials:
      access-key: AKIATIVNZLQ23AQR4MPK
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
spring:
  django-url: internal-preprocess-73917218.us-east-2.elb.amazonaws.com:80
  autoconfigure:
    exclude : org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=UTF-8
    username: admin #root - local admin- aws
    password: password
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  data:
    redis:
      host: localhost
      port: 6379
server:
  servlet:
    session:
      timeout: 600